import { afterAll, beforeAll, describe, expect, spyOn, test } from 'bun:test';
import { randomUUID } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { Client } from 'typesense';
import { searchDocs } from '../../client/search';
import {
  getDefaultCollectionFields,
  sync,
  type DocumentRecord,
  type TypesenseDocument,
} from '../../index';

const typesenseHost = process.env.TYPESENSE_HOST ?? '127.0.0.1';
const typesensePort = Number(process.env.TYPESENSE_PORT ?? '8108');
const typesenseProtocol = getTypesenseProtocol(process.env.TYPESENSE_PROTOCOL);
const typesenseApiKey = process.env.TYPESENSE_API_KEY ?? 'xyz';
const runPrefix = `fumadocs_adapter_it_${Date.now()}_${randomUUID().replaceAll('-', '')}`;
const docsIndexPath = resolve(
  import.meta.dir,
  '../../../../docs/.next/server/app/static.json.body',
);

const client = new Client({
  nodes: [
    {
      host: typesenseHost,
      port: typesensePort,
      protocol: typesenseProtocol,
    },
  ],
  apiKey: typesenseApiKey,
  connectionTimeoutSeconds: 5,
  numRetries: 0,
});

let docsRecords: DocumentRecord[] = [];
let typesenseAvailable = false;

function getTypesenseProtocol(value: string | undefined): 'http' | 'https' {
  if (value === undefined || value === 'http') return 'http';
  if (value === 'https') return 'https';

  throw new Error(
    `Unsupported TYPESENSE_PROTOCOL value: ${value}. Expected \`http\` or \`https\`.`,
  );
}

function collectionName(testName: string): string {
  return `${runPrefix}_${testName}`;
}

function recordsForLocale(locale: string, tag: string): DocumentRecord[] {
  return docsRecords
    .filter((record) => record.locale === locale)
    .map((record) => ({ ...record, tag }));
}

async function removeTestResources(): Promise<void> {
  const { aliases } = await client.aliases().retrieve();

  for (const alias of aliases) {
    if (alias.name.startsWith(runPrefix)) {
      await client.aliases(alias.name).delete();
    }
  }

  const collections = await client.collections().retrieve();

  for (const collection of collections) {
    if (collection.name.startsWith(runPrefix)) {
      await client.collections(collection.name).delete();
    }
  }
}

beforeAll(async () => {
  try {
    await client.health.retrieve();
    typesenseAvailable = true;
  } catch (error) {
    throw new Error(
      `Typesense is unavailable at ${typesenseProtocol}://${typesenseHost}:${typesensePort}. Run \`docker compose up -d typesense\` first.`,
      { cause: error },
    );
  }

  try {
    docsRecords = JSON.parse(
      await readFile(docsIndexPath, 'utf8'),
    ) as DocumentRecord[];
  } catch (error) {
    throw new Error(
      'The Fumadocs search index fixture is missing. Run `bun run test:integration:prepare` from the repository root.',
      { cause: error },
    );
  }

  if (docsRecords.length === 0) {
    throw new Error(`The Fumadocs search index at ${docsIndexPath} is empty.`);
  }
});

afterAll(async () => {
  if (typesenseAvailable) {
    await removeTestResources();
  }
});

describe('Typesense adapter integration', () => {
  test('indexes and searches localized records generated by the docs app', async () => {
    const aliasName = collectionName('localized');
    const records = docsRecords.map((record) => ({
      ...record,
      tag: 'latest',
    }));

    await sync(client, {
      typesenseCollectionName: aliasName,
      documents: records,
    });

    const locales = [
      ...new Set(
        records.flatMap((record) =>
          record.locale === undefined ? [] : [record.locale],
        ),
      ),
    ];
    expect(locales.length).toBeGreaterThan(1);

    for (const locale of locales) {
      const localizedAlias = await client
        .aliases(`${aliasName}_${locale}`)
        .retrieve();
      const schema = await client
        .collections(localizedAlias.collection_name)
        .retrieve();
      const tagField = schema.fields?.find((field) => field.name === 'tag');

      expect(tagField).toMatchObject({
        name: 'tag',
        type: 'string',
        facet: true,
        optional: true,
      });
      expect(schema.num_documents).toBeGreaterThan(0);
    }

    const englishRecord = records.find(
      (record) => record.locale === 'en' && record.description,
    );
    if (englishRecord?.description === undefined) {
      throw new Error('The docs fixture has no English record with a description.');
    }

    const matching = await searchDocs(englishRecord.description, {
      typesenseCollectionName: aliasName,
      client,
      locale: 'en',
      tag: 'latest',
    });
    const filteredOut = await searchDocs(englishRecord.description, {
      typesenseCollectionName: aliasName,
      client,
      locale: 'en',
      tag: 'archived',
    });

    expect(matching.raw.found).toBeGreaterThan(0);
    expect(
      matching.results.some(
        (result) =>
          result.type === 'page' && result.url === englishRecord.url,
      ),
    ).toBe(true);
    expect(filteredOut.raw.found).toBe(0);
    expect(filteredOut.results).toEqual([]);
  });

  test('atomically replaces the alias and removes the old collection', async () => {
    const aliasName = collectionName('replace');
    const initialRecords = recordsForLocale('en', 'initial');

    await sync(client, {
      typesenseCollectionName: aliasName,
      documents: initialRecords,
    });
    const initialAlias = await client.aliases(aliasName).retrieve();

    await Bun.sleep(2);

    const replacementRecords = initialRecords.map((record, index) => ({
      ...record,
      description:
        index === 0 ? 'Atomic replacement marker' : record.description,
      tag: 'replacement',
    }));

    await sync(client, {
      typesenseCollectionName: aliasName,
      documents: replacementRecords,
    });
    const replacementAlias = await client.aliases(aliasName).retrieve();

    expect(replacementAlias.collection_name).not.toBe(
      initialAlias.collection_name,
    );
    let oldCollectionError: unknown;
    try {
      await client.collections(initialAlias.collection_name).retrieve();
    } catch (error) {
      oldCollectionError = error;
    }
    expect(oldCollectionError).toMatchObject({ httpStatus: 404 });

    const replacementSearch = await client
      .collections<TypesenseDocument>(aliasName)
      .documents()
      .search({
        q: 'Atomic replacement marker',
        query_by: 'content',
      });

    expect(replacementSearch.found).toBeGreaterThan(0);
  });

  test('preserves the working alias and collection when an import fails', async () => {
    const aliasName = collectionName('failed_import');
    const workingRecords = recordsForLocale('en', 'working');

    await sync(client, {
      typesenseCollectionName: aliasName,
      documents: workingRecords,
    });
    const workingAlias = await client.aliases(aliasName).retrieve();
    const workingSchema = await client
      .collections(workingAlias.collection_name)
      .retrieve();
    const logMessages: string[] = [];
    const logSpy = spyOn(console, 'log').mockImplementation((...args) => {
      logMessages.push(args.map(String).join(' '));
    });

    try {
      await expect(
        sync(client, {
          typesenseCollectionName: aliasName,
          documents: workingRecords,
          customLocaleCollectionSettings: {
            en: {
              field_definitions: [
                ...getDefaultCollectionFields('en'),
                { name: 'required_extra', type: 'string' },
              ],
            },
          },
        }),
      ).rejects.toThrow(/Failed to import some records|documents failed/);
    } finally {
      logSpy.mockRestore();
    }

    const preservedAlias = await client.aliases(aliasName).retrieve();
    const preservedSchema = await client
      .collections(workingAlias.collection_name)
      .retrieve();

    expect(preservedAlias.collection_name).toBe(workingAlias.collection_name);
    expect(preservedSchema.num_documents).toBe(workingSchema.num_documents);
    expect(
      logMessages.some((message) => message.includes('Syncing Complete')),
    ).toBe(false);
  });
});
